## TravisCI config
#
sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
    ## From: http://conda.pydata.org/docs/travis.htm
    ## Another one: https://gist.github.com/dan-blanchard/7045057
    #- sudo apt-get update
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - |
        export PATH="$HOME/miniconda/bin:$PATH"
        hash -r
    - |
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda

    ## Print python-version and architecture for debugging .
    #
    - |
        python --version
        conda info -a


install:
    - |
        deps="`grep -v \# requirements/miniconda.conda`"
        conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION $deps

    - source activate test-environment
    - pip install -r requirements/development.pip

    ## TODO: Check if FIXED ``python setup.py nosetests`` failing with conda:
    #   https://github.com/ContinuumIO/anaconda-issues/issues/280
    - |
        pip uninstall -y nose
        pip uninstall -y nose
        pip install -UI nose

    # - "python setup.py develop" ## NO, pip installed in "develop' mode, above.
    - python setup.py build

script:
    - |
        echo "+++ Checking README for PyPy...."
        ./bin/check_readme.sh

    - |
        echo "+++ Checking site...."
        python setup.py build_sphinx

    #Why started failing on Travis since v0.1.6?
    #- |
    #
    #    echo "+++  Checking archives for PyPI repo..."
    #    python setup.py sdist bdist_wheel

    - |
        if [[ "$TRAVIS_PYTHON_VERSION" = '3.4' ]]; then
            echo "+++ Checking all TCs, DTs & Coverage....";
            python setup.py test_all
        else
            echo "+++ Checking only TCs....";
            python setup.py test_code
        fi

    -   echo "+++ Checking install...."
        python setup.py install

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then coveralls; fi

